Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from os import path
import os

if path.isdir('analysis')== False:
    !git clone https://github.com/courtois-neuromod/anat-processing-book.git analysis
    dir_name = 'analysis'
    analysis = os.listdir(dir_name)

    for item in analysis:
        if item.endswith(".ipynb"):
            os.remove(os.path.join(dir_name, item))
        if item.endswith(".md"):
            os.remove(os.path.join(dir_name, item))

cwd = os.getcwd()
os.chdir('analysis/source')

from tools.data import *
from tools.plot import *
from tools.stats import *

os.chdir(cwd)

# Python imports 
from IPython.display import clear_output
from pathlib import Path
import numpy as np

import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 1)

data_type = 'brain'
release_version = 'latest'

dataset = Data(data_type)
dataset.data_dir = os.path.join(data_path,data_type)

# if build == 'latest':
#     dataset.download(release_version)
# elif build == 'archive':
#     dataset.data_dir = Path('analysis/source/data/brain')

dataset.load()
fig_gm = Plot(dataset, plot_name = 'brain-1')

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 47[0m
[1;32m     40[0m dataset[38;5;241m.[39mdata_dir [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(data_path,data_type)
[1;32m     42[0m [38;5;66;03m# if build == 'latest':[39;00m
[1;32m     43[0m [38;5;66;03m#     dataset.download(release_version)[39;00m
[1;32m     44[0m [38;5;66;03m# elif build == 'archive':[39;00m
[1;32m     45[0m [38;5;66;03m#     dataset.data_dir = Path('analysis/source/data/brain')[39;00m
[0;32m---> 47[0m [43mdataset[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43m)[49m
[1;32m     48[0m fig_gm [38;5;241m=[39m Plot(dataset, plot_name [38;5;241m=[39m [38;5;124m'[39m[38;5;124mbrain-1[39m[38;5;124m'[39m)

File [0;32m~/work/anat-processing-paper/anat-processing-paper/content/analysis/source/tools/data.py:139[0m, in [0;36mData.load[0;34m(self)[0m
[1;32m    137[0m [38;5;28;01mif[39;00m data_type [38;5;241m==[39m [38;5;124m'[39m[38;5;124mbrain[39m[38;5;124m'[39m [38;5;129;01mor[39;00m data_type [38;5;241m==[39m [38;5;124m'[39m[38;5;124mbrain-diffusion-cc[39m[38;5;124m'[39m:
[1;32m    138[0m     data_file [38;5;241m=[39m Data[38;5;241m.[39mdatasets[data_type][[38;5;124m'[39m[38;5;124mdata_files[39m[38;5;124m'[39m]
[0;32m--> 139[0m     file_path [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdata_dir[49m[43m [49m[38;5;241;43m/[39;49m[43m [49m[43mdata_file[49m
[1;32m    141[0m     [38;5;66;03m# Read data[39;00m
[1;32m    142[0m     [38;5;28mself[39m[38;5;241m.[39mdata [38;5;241m=[39m pd[38;5;241m.[39mread_csv(file_path, converters[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mproject_id[39m[38;5;124m'[39m: [38;5;28;01mlambda[39;00m x: [38;5;28mstr[39m(x)})

[0;31mTypeError[0m: unsupported operand type(s) for /: 'str' and 'str'
TypeError: unsupported operand type(s) for /: 'str' and 'str'

